/*
 * JSP generated by Resin 2.1.14 (built Thu Jul  1 18:39:55 PDT 2004)
 */

import java.util.List;

import javax.servlet.jsp.JspFactory;

import com.msn.cbbp.workflow.SampleWorkflowSessions;
import com.msn.cbbp.workflow.UserVariant;
import com.msn.cbbp.workflow.WorkflowSession;

public class _mailwait__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, null, true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html; charset=Big5");
    request.setCharacterEncoding("Big5");
    try {
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      
	WorkflowSession wfsession=SampleWorkflowSessions.getSampleWorkflowSession();
	List inputList=wfsession.getVariantList();
	for(int i=0;i<inputList.size();i++){
		UserVariant input=(UserVariant)inputList.get(i);
	
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      out.print((input.getName()));
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((input.getValue()));
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      
	
	}

      pageContext.write(_jsp_string5, 0, _jsp_string5.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -2089842221)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_mailwait__jsp.java", "/workflow/mailwait.jsp");
    _caucho_line_map.add(4, 1);
    _caucho_line_map.add(2, 29);
    _caucho_line_map.add(16, 32);
    _caucho_line_map.add(22, 39);
    _caucho_line_map.add(22, 41);
    _caucho_line_map.add(23, 43);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("mailwait.jsp"), 1110722832000L, 808L);
    _caucho_depends.add(depend);
  }

  protected void _caucho_clearDepends()
  {
    _caucho_depends.clear();
  }

  private static byte []_jsp_string2;
  private static byte []_jsp_string3;
  private static byte []_jsp_string5;
  private static byte []_jsp_string4;
  private static byte []_jsp_string1;
  private static byte []_jsp_string0;
  static {
    try {
      _jsp_string2 = "\r\n	<input type='hidden' name='".getBytes("BIG5");
      _jsp_string3 = "' value='".getBytes("BIG5");
      _jsp_string5 = "\r\n</form>\r\n\r\n<script>\r\n	document.submitdata.submit();\r\n	//window.location='workflow.jsp';\r\n\r\n</script>\r\n</html>".getBytes("BIG5");
      _jsp_string4 = "'>\r\n	".getBytes("BIG5");
      _jsp_string1 = "\r\n\r\n<html>\r\n<head>\r\n<!-- \u52a0\u4e0a\u4ee5\u4e0b\u9019\u4e00\u884c\uff0c\u4ee5\u514d\u6709\u4e82\u78bc\u7522\u751f -->\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=big5\">\r\n<title>\u7559\u8a00\u677f</title>\r\n</head>\r\n\r\n\u6b63\u5728\u8655\u7406\uff0c \u8acb\u7b49\u5f85...................\r\n\r\n<form action='mail.jsp' name='submitdata'>\r\n".getBytes("BIG5");
      _jsp_string0 = "\r\n".getBytes("BIG5");
    } catch (java.io.UnsupportedEncodingException e) {
      e.printStackTrace();
    }
  }
}
