/*
 * JSP generated by Resin 2.1.16 (built Tue Feb 15 11:12:27 PST 2005)
 */

import java.util.List;

import javax.servlet.jsp.JspFactory;

import com.msn.cbbp.workflow.Action;
import com.msn.cbbp.workflow.Activity;
import com.msn.cbbp.workflow.Input;
import com.msn.cbbp.workflow.SampleWorkflowSessions;
import com.msn.cbbp.workflow.VariantTool;
import com.msn.cbbp.workflow.WorkflowSession;

public class _showwml__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, null, true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/vnd.wap.wml");
    try {
      

	WorkflowSession wfsession=SampleWorkflowSessions.getSampleWorkflowSession();
	Activity activity=wfsession.getCurrentActivity();
	
	List actionList =activity.getActionList();
	List inputList =activity.getInputList();
	


      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      out.print((activity.getLabel()));
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      

	for(int i=0;i<inputList.size();i++){
		Input input=(Input)inputList.get(i);
		String value=wfsession.parseMessage(input.getValue());
	
      pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      out.print((input.getLabel()));
      pageContext.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((input.getName()));
      pageContext.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((VariantTool.toTextUTF(value)));
      pageContext.write(_jsp_string5, 0, _jsp_string5.length);
      
	
	}

      pageContext.write(_jsp_string6, 0, _jsp_string6.length);
      
	String actions="|";
	for(int i=0;i<actionList.size();i++){
		Action action=(Action)actionList.get(i);
		actions+=action.getEvent()+"|";
	
      pageContext.write(_jsp_string7, 0, _jsp_string7.length);
      out.print((action.getEvent()));
      pageContext.write(_jsp_string8, 0, _jsp_string8.length);
      out.print((action.getLabel()));
      pageContext.write(_jsp_string9, 0, _jsp_string9.length);
      
	
	}

      pageContext.write(_jsp_string10, 0, _jsp_string10.length);
      

	for(int i=0;i<inputList.size();i++){
		Input input=(Input)inputList.get(i);
		String value=wfsession.parseMessage(input.getValue());
	
      pageContext.write(_jsp_string11, 0, _jsp_string11.length);
      out.print((input.getName()));
      pageContext.write(_jsp_string12, 0, _jsp_string12.length);
      out.print((input.getName()));
      pageContext.write(_jsp_string13, 0, _jsp_string13.length);
      
	
	}

      pageContext.write(_jsp_string14, 0, _jsp_string14.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -2089842219)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_showwml__jsp.java", "/workflow/showwml.jsp");
    _caucho_line_map.add(1, 1);
    _caucho_line_map.add(1, 29);
    _caucho_line_map.add(15, 40);
    _caucho_line_map.add(22, 42);
    _caucho_line_map.add(28, 49);
    _caucho_line_map.add(28, 51);
    _caucho_line_map.add(28, 53);
    _caucho_line_map.add(29, 55);
    _caucho_line_map.add(35, 60);
    _caucho_line_map.add(41, 67);
    _caucho_line_map.add(41, 69);
    _caucho_line_map.add(42, 71);
    _caucho_line_map.add(54, 76);
    _caucho_line_map.add(60, 83);
    _caucho_line_map.add(60, 85);
    _caucho_line_map.add(61, 87);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("showwml.jsp"), 1112459479687L, 1847L);
    _caucho_depends.add(depend);
  }

  protected void _caucho_clearDepends()
  {
    _caucho_depends.clear();
  }

  private static byte []_jsp_string4;
  private static byte []_jsp_string7;
  private static byte []_jsp_string11;
  private static byte []_jsp_string3;
  private static byte []_jsp_string0;
  private static byte []_jsp_string2;
  private static byte []_jsp_string12;
  private static byte []_jsp_string10;
  private static byte []_jsp_string14;
  private static byte []_jsp_string6;
  private static byte []_jsp_string5;
  private static byte []_jsp_string1;
  private static byte []_jsp_string9;
  private static byte []_jsp_string13;
  private static byte []_jsp_string8;
  static {
    _jsp_string4 = "' value='".getBytes();
    _jsp_string7 = "	\r\n	<option value=\"".getBytes();
    _jsp_string11 = "\r\n			<postfield name=\"".getBytes();
    _jsp_string3 = ": <input  name='".getBytes();
    _jsp_string0 = "<?xml version=\"1.0\"?>\r\n<!DOCTYPE wml PUBLIC \"-//WAPFORUM//DTD WML 1.1//EN\" \"http://www.wapforum.org/DTD/wml_1.1.xml\">\r\n<!-- Source Generated by WML Deck Decoder -->\r\n\r\n<wml>\r\n  <card id=\"home\" title=\"".getBytes();
    _jsp_string2 = "\r\n	".getBytes();
    _jsp_string12 = "\" value=\"$".getBytes();
    _jsp_string10 = "\r\n	\r\n    </select>\r\n    </p>\r\n    <p>\r\n        <do type=\"accept\" label=\"submit\">\r\n        	<go href=\"wmlworkflow.jsp\" method=\"get\">\r\n        		<postfield name=\"event\" value=\"$event\"/>\r\n\r\n ".getBytes();
    _jsp_string14 = "       	\r\n        	</go>\r\n        </do>\r\n    </p>\r\n  </card>\r\n  \r\n\r\n</wml>".getBytes();
    _jsp_string6 = "\r\n    \r\n    <select name=\"event\" value=\"0\" title=\"Select\">\r\n".getBytes();
    _jsp_string5 = "'/>\r\n	".getBytes();
    _jsp_string1 = "\" newcontext=\"true\">\r\n    <p >\r\n	<em>login</em>\r\n	<img  localsrc=\"house\" alt=\"ss\" src=\"\"/>\r\n    </p>\r\n    <p>\r\n    \r\n".getBytes();
    _jsp_string9 = "</option>\r\n	".getBytes();
    _jsp_string13 = "\"/>\r\n	".getBytes();
    _jsp_string8 = "\">".getBytes();
  }
}
